Merge pull request #2813 in TAB/tabula from TAB-7482-take-3 to develop
Squashed commit of the following:

commit dd1c31925f02d18fc374f7805ea58e902559f61f
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 13:45:49 2019 +0100

    TAB-7482 update tests according (missed this one previously)

commit 72c67ed867337956eafd614f8f393cd969caf388
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 13:31:48 2019 +0100

    TAB-7482 adjust formatting to make it more readable

commit 06d8b31e2f02ff74d375a77f35644b0f38cc4643
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 11:46:45 2019 +0100

    TAB-7482 update tests accordingly

commit e50b7c87d7bb622357011e1fd63aac578d386752
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 11:45:51 2019 +0100

    TAB-7482 update accordingly to remove the no-longer-needed stripHtml

commit c15f1944e86995ebc55277d79fdaf48ce39f01de
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 11:24:48 2019 +0100

    TAB-7482 update tests accordingly WIP

commit 53fbbf033ea685b4e02a1633042beb3e4ea614f1
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 10:58:54 2019 +0100

    TAB-7482 typo WIP

commit d2c6f0920f98e9e1bb920e37abb4fcd5937e5adc
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Fri Aug 23 10:54:46 2019 +0100

    TAB-7482 remove stripHtml option WIP

commit c41624ac9c80daafeda3b1b13cab94e69ec164ff
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 16:50:05 2019 +0100

    TAB-7482 typo in unit test

commit b4da790c8a43f5f756c2854fbd4603e088e34c86
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 15:35:04 2019 +0100

    TAB-7482 fix some broken code (by typo) found by tests

commit 639c120069c48f3f21264829514e7d0857951e80
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 15:19:51 2019 +0100

    TAB-7482 fix some broken tests WIP

commit 0f81d81faa80db4a15b42ae9cf03542b11b50b0b
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 14:33:04 2019 +0100

    TAB-7482 fixe broken tests

commit 8f6abe337b5677f5e16eda5a3ad8493f8c267f88
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 14:07:41 2019 +0100

    TAB-7482 update tests accordingly

commit 36ea5a6df3ae50399c6e4c8f2f2b15a194d65a07
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 14:07:22 2019 +0100

    TAB-7482 use it

commit 4e21719c24f17ecbc4df767011e86e14d9e96a16
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 13:26:18 2019 +0100

    TAB-7482 fix compilation error: multiple overloaded alternatives of method format define default arguments WIP

commit 3c13117f459558913279892d81f998f2992c089c
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 13:20:26 2019 +0100

    TAB-7482 fix compilation error: multiple overloaded alternatives of method format define default arguments WIP

commit b48e6463b22ce27dca426f05b55f68ef2eb29036
Merge: 8c461c8326 522fa7a487
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 11:53:16 2019 +0100

    Merge remote-tracking branch 'origin/develop' into TAB-7482-take-3

commit 8c461c83269ede5dbbe93ab719188ca955f3c4c0
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 11:53:07 2019 +0100

    TAB-7482 add stripHtml parameter to the tag WIP

commit 2128d7aca0429fbc9ec1bc105d3925fea33c4400
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 11:34:59 2019 +0100

    TAB-7482 add ordinal map for super text

commit 0579a3bc5395d58f0d7bc93ba32d55fac00a6cb3
Author: Kai Lan <k.lan@warwick.ac.uk>
Date:   Thu Aug 22 10:10:24 2019 +0100

    TAB-7482 wip